let restaurantesBirigui = [
    {
        nomeRestaurante: 'FRUTYDELLYS DR GAMA SORVETERIA',
        cep: '16200-001',
        endereco: 'R. Barão do Rio Branco, 116 - Centro, Birigui - SP',
        telefone: '(18) 3638-4942',
        categoria: 'Sorveteria',
        horarioFuncionamento:
            '11:00h até 23:00h | 12:00h até 23:00h (Sábado e Domingo)',
    },
    {
        nomeRestaurante: 'Macaúba Restaurante',
        cep: '16203-098',
        endereco: 'Rua Bom Jesus, 1225 - Vila Bandeirantes, Birigui - SP',
        telefone: '(18) 3638-4777',
        categoria: 'Restaurante',
        horarioFuncionamento: '08:00h até 14:00h | 18:00h até 23:00h (Segunda)',
    },
    {
        nomeRestaurante: 'Pizzaria Pérola',
        cep: '16201-413',
        endereco:
            'Avenida Afife José Abdo, 902 - Portal da Pérola 2, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Pizzaria, Restaurante',
        horarioFuncionamento: '18:00h até 00:00h',
    },
    {
        nomeRestaurante: 'Esquina do Cupim',
        cep: '16200-767',
        endereco:
            'Avenida Nove de Julho, 1145 - Jardim Nossa Senhora de Fátima, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '18:00h até 23:00h',
    },
    {
        nomeRestaurante: 'Sabor Maneiro Restaurante e Marmitex',
        cep: '16201-310',
        endereco: 'Rua Natal Masson, 451 - Residencial Simões, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '10:30h até 14:30h',
    },
    {
        nomeRestaurante: 'Beliscão Restaurante & Sushi Bar',
        cep: '16200-071',
        endereco: 'Rua Ribeiro de Barros, 305 - Centro, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante, Sushi Bar',
        horarioFuncionamento: '18:30h até 00:00h',
    },
    {
        nomeRestaurante: 'Aiko Japanese Food',
        cep: '16200-008',
        endereco: 'Rua Saudades, 1685 - Centro, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: 'Não disponível',
    },
    {
        nomeRestaurante: 'Restaurante Trem Bão',
        cep: 'Não disponível',
        endereco: 'Não disponível',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '10:30h até 14:30h',
    },
    {
        nomeRestaurante: 'Jordão Espetaria & Porções',
        cep: '16200-840',
        endereco:
            'Rodovia Gabriel Melhado, 19 - Patrimonio Santo Antonio, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '18:00h até 00:00h',
    },
    {
        nomeRestaurante: 'Restaurante e Lanchonete Sabor Real',
        cep: '16200-053',
        endereco: 'Rua Bento da Cruz, 160 - Centro, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante, Lanchonete',
        horarioFuncionamento: '08:00h até 16:00h',
    },
    {
        nomeRestaurante: 'Rossi Restaurante',
        cep: '16204-000',
        endereco:
            'Avenida Euclides Miragaia, 1792 - Jardim Jussara Maria, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '10:30h até 14:30h',
    },
    {
        nomeRestaurante: 'Purus Bistrô',
        cep: '16200-004',
        endereco: 'Rua Maestro Antonio Passarelli, 0 - Centro, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante, Bistrô',
        horarioFuncionamento: '11:00h até 15:00h',
    },
    {
        nomeRestaurante: 'Barroco Carnes e Pastas',
        cep: '16201-013',
        endereco: 'Rua Silvares, 330 - Patrimônio Silvares, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '19:00h até 23:30h',
    },
    {
        nomeRestaurante: 'Casa do Norte',
        cep: '16200-055',
        endereco: 'Rua Siqueira Campos, 65, Sl 1 e 2 - Centro, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '08:00h até 18:30h',
    },
    {
        nomeRestaurante: 'Cantinho do Sabor',
        cep: '16200-700',
        endereco: 'Avenida Nove de Julho, 2213 - Jardim Stábile, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '11:00h até 14:00h',
    },
    {
        nomeRestaurante: 'Saab Bar e Restaurante',
        cep: '16203-054',
        endereco:
            'Avenida Euclides Miragaia, 2474 - Jardim Pinheiros, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '10:00h até 13:30h',
    },
    {
        nomeRestaurante: 'Divina Mesa Rotisserie',
        cep: '16204-044',
        endereco:
            'Rua Manoel Marin Berbel, 2171 - Vila Isabel Marin, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: 'Não disponível',
    },
    {
        nomeRestaurante: 'Casa Mineira',
        cep: '16203-053',
        endereco: 'Rua Elias Antônio, 226 - Jardim Pinheiros, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '07:00h até 14:00h',
    },
    {
        nomeRestaurante: 'Restaurante Dona Cida',
        cep: '16203-165',
        endereco: 'Avenida Vitória Régia, 2192 - Cidade Jardim, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: 'Fechado',
    },
    {
        nomeRestaurante: 'Restaurante Natural da Terra',
        cep: '16201-021',
        endereco: 'Rua Euclides da Cunha, 286 - Vila Silvares, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '10:30h até 15:00h',
    },
    {
        nomeRestaurante: 'Tempero Manero',
        cep: '16200-027',
        endereco: 'Rua Antônio Simões, 196 - Centro, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: '11:00h até 14:00h',
    },
    {
        nomeRestaurante: 'Baviera Bier',
        cep: '16201-020',
        endereco: 'Rua Maria Dolores Nunes, 1017 - Vila Silvares, Birigui - SP',
        telefone: 'Não disponível',
        categoria: 'Restaurante',
        horarioFuncionamento: 'Não disponível',
    },
];
